<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Rule10MagicadSystemFromConnectedStraight.DevKit</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\Rule10MagicadSystemFromConnectedStraight.cs" Link="Rule10MagicadSystemFromConnectedStraight.cs" />
  </ItemGroup>
</Project>